# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  ACRServiceConnection: '{DevOps에 등록한 ACR ServiceConnection 이름을 적어주세요.}'
  imageRepository: 'challingedev'
  imageRepository2: 'challingeprod'
  dockerfilePath: '$(Build.SourcesDirectory)/{Dev 환경의 Dockerimage파일이 있는 경로를 적어주세요.}'
  dockerfilePath2: '$(Build.SourcesDirectory)/{Prod 환경의 Dockerimage파일이 있는 경로를 적어주세요.}'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildDev
  displayName: Build-dev image
  jobs:
  - job: Build
    displayName: Build-dev
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        command: 'BuildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(ACRServiceConnection)
        tags: |
          $(tag)
- stage: BuildProd
  displayName: Build-prod image
  jobs:
  - job: Build
    displayName: Build-prod
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        command: 'BuildAndPush'
        repository: $(imageRepository2)
        Dockerfile: $(dockerfilePath2)
        containerRegistry: $(ACRServiceConnection)
        tags: |
          $(tag)