apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-deployment
  labels:
    app: nginx_prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx_prod
  template:
    metadata:
      labels:
        app: nginx_prod
    spec:
      containers:
      - name: sprint-prod
        image: {Docker 이미지를 가져오기 위한 URL을 지정해주세요.}
        ports:
        - containerPort: 80
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nginxprod
spec:
  selector:
    app: nginx_prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprintingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/override-frontend-port: "80"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: nginxprod
            port: 
              number: 80
        pathType: Prefix